export enum Parametertype {
  FEDREKVOTE_DAGER = 'FEDREKVOTE_DAGER',
  MØDREKVOTE_DAGER = 'MØDREKVOTE_DAGER',
  FELLESPERIODE_DAGER = 'FELLESPERIODE_DAGER',
  FORELDREPENGER_MOR_ELLER_ALENEOMSORG_DAGER = 'FORELDREPENGER_MOR_ELLER_ALENEOMSORG_DAGER',
  FORELDREPENGER_BARE_FAR_RETT_DAGER = 'FORELDREPENGER_BARE_FAR_RETT_DAGER',
  FORELDREPENGER_FØR_FØDSEL = 'FORELDREPENGER_FØR_FØDSEL',

  EKSTRA_DAGER_TO_BARN = 'EKSTRA_DAGER_TO_BARN',
  EKSTRA_DAGER_TRE_ELLER_FLERE_BARN = 'EKSTRA_DAGER_TRE_ELLER_FLERE_BARN',

  BARE_FAR_RETT_MOR_UFØR_DAGER_UTEN_AKTIVITETSKRAV = 'BARE_FAR_RETT_MOR_UFØR_DAGER_UTEN_AKTIVITETSKRAV',

  BARE_FAR_RETT_DAGER_MINSTERETT = 'BARE_FAR_RETT_DAGER_MINSTERETT',
  BARE_FAR_RETT_MOR_UFØR_DAGER_MINSTERETT = 'BARE_FAR_RETT_MOR_UFØR_DAGER_MINSTERETT',
  MOR_TETTE_SAKER_DAGER_FØDSEL = 'MOR_TETTE_SAKER_DAGER_FØDSEL',
  MOR_TETTE_SAKER_DAGER_ADOPSJON = 'MOR_TETTE_SAKER_DAGER_ADOPSJON',
  FAR_TETTE_SAKER_DAGER = 'FAR_TETTE_SAKER_DAGER',

  FAR_DAGER_RUNDT_FØDSEL = 'FAR_DAGER_RUNDT_FØDSEL',
}

