package no.nav.foreldrepenger.stønadskonto.regelmodell.konfig;

public enum Parametertype {

    // Stønadskontoer gitt dekningsgrad
    EKSTRA_DAGER_TO_BARN,
    EKSTRA_DAGER_TRE_ELLER_FLERE_BARN,
    FEDREKVOTE_DAGER,
    MØDREKVOTE_DAGER,
    FELLESPERIODE_DAGER,
    FORELDREPENGER_MOR_ALENEOMSORG_DAGER,
    FORELDREPENGER_BARE_FAR_RETT_DAGER,
    FORELDREPENGER_FØR_FØDSEL,

    // Andre rettigheter gitt dekningsgrad
    BARE_FAR_RETT_MOR_UFØR_DAGER_UTEN_AKTIVITETSKRAV,
    BARE_FAR_RETT_MOR_UFØR_DAGER_MINSTERETT,

    //Rettigheter utenom konti
    BARE_FAR_RETT_DAGER_MINSTERETT,
    MOR_TETTE_SAKER_DAGER_FØDSEL,
    MOR_TETTE_SAKER_DAGER_ADOPSJON,
    FAR_TETTE_SAKER_DAGER_MINSTERETT,
    FAR_DAGER_RUNDT_FØDSEL,

    //Grenser
    PREMATURUKER_ANTALL_DAGER_FØR_TERMIN,
    TETTE_SAKER_MELLOMROM_UKER;

}
